server:
  port: 9090
  
spring:
  application:
    name: customer-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/customers
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8762/eureka/    