server:
  port: 9000
spring:
  application:
    name: authorization-server
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/user
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
    
    
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
    
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8762/eureka/
     
          
