server:
  port: 9092
spring:
  application:
    name: account-service
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/accounts
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8762/eureka/
            
          
